name: Build
on:
  push:
    branches:
      - main
      - develop
      - 'feature/**'
env:
  MAVEN_OPTS: '-Dstyle.color=always -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer=warn'
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: Set up GraalVM Native Image toolchain
        uses: helpermethod/graalvm-native-image-toolchain@0.0.2
        with:
          java-version: '17'
          graalvm-version: '22.2.0'
      - name: build
        run: mvn -B verify
      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v3
        with:
          name: msx executable
          path: 'msx/target/deploy/**'
          retention-days: 10
